### ISSUE TITLE
Changes in category and sub-category part

### ISSUE THREAD

**Issue by kumarsw** [prakashscoopwhoop/BlackBird#1]
As per our discussion, we have to refactor category and subcategory collection.
According to new collection schema, we need to change api as well

**Comment by kumarsw** [comment]
I think, we should add keywords as per interests(sub-category). It'll helpful in articles classification.
Dictionary would be like this... {"_id": "a21a2...", "category_id": "34bae3...", "subcategory": "Politics", "keywords": ["Minister", "Elections", "cabinet", "MLA", "Politician"]}.
For now, we'll keep keywords as empty array. And we'll use it in next phase of articles classification.

**Comment by prakashscoopwhoop** [comment]
As per our discussion,  i will change the schema of interest.
Now there are two separate collections i.e 1. category 2. interest(sub_category).
category contains only category_name and _id
Interest contains : _id,sub_category_name,category_id,image,keywords
